name: Password Manager Frontend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          EC2_IP: ${{ secrets.EC2_IP }}
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@$EC2_IP << 'EOF'
            cd ~/password-manager-frontend
            git fetch origin main
            git stash
            git checkout main
            git pull origin main
            git stash pop || true

            # Load NVM and use the correct Node.js version
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 20.18.0 || nvm install 20.18.0

            npm ci
            npm run build
            sudo cp -R dist/* /var/www/frontend/
            sudo systemctl restart nginx
          EOF
