name: Password Manager Backend

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_IP }} << 'EOF'
            cd password-manager-frontend
            git stash
            git pull origin main
            
            npm install
            npm run build

            git stash pop
            npm install
            npm run build
            sudo cp -R dist/ /var/www/frontend
            sudo systemctl daemon-reload
            sudo systemctl restart nginx
          EOF
